app/__init__.py
from flask import Flask
from config import Config
import os
import click
from flask_wtf.csrf import CSRFProtect


app= Flask(__name__)
app.config.from_object(Config)
csrf = CSRFProtect()
csrf.init_app(app)

def reregister_bp():
    from app.blueprint.auth import auth_bp
    from app.blueprint.student import student_bp
    from app.blueprint.manage import manage_bp
    app.register_blueprint(auth_bp)
    app.register_blueprint(student_bp)
    app.register_blueprint(manage_bp)

reregister_bp()

from . import cmd

app/blueprint/auth.py
from flask import render_template,flash,redirect,request,session,url_for,jsonify,Blueprint
from app.db import check_passwd,set_passwd,test
from app.unity import required_login,is_sa

auth_bp = Blueprint('auth', __name__)



@auth_bp.route("/changePasswd",methods=["GET",'POST'])
@required_login
def change_passwd():
    if request.method == "POST":
        data = request.get_json()
        if data["new_passwd"] !=  data["comfirmed_passwd"]:
            return jsonify(error='两次输入密码不一致')
        elif check_passwd( session["id"], data["old_passwd"] ):
            set_passwd(session["id"] , data["new_passwd"] ) 
            return jsonify(message = '密码修改成功',_type='success')
        else:
            return jsonify(message = '密码不正确',_type='warning')
    return render_template('auth/change_passwd.html')


@auth_bp.route("/login",methods = ["GET","POST"]) 
def login():
    if 'id' in session:
        return redirect(url_for('manage.index'))
    if request.method == 'POST':
        id = request.form.get("sno",None)
        passwd = request.form.get("passwd",None)
        if not(id and passwd):
            flash("密码和学号不能为空")
        if not check_passwd(id,passwd):
            flash("密码与学号不匹配")
            return render_template("auth/signin.html")
        else:
            session['id'] = id
            if is_sa():
                return redirect(url_for('manage.index'))
            else:
                return redirect(url_for('student.index'))
        
    return render_template("auth/signin.html")

@auth_bp.route("/logout",methods=["GET","POST"])
def logout():
    if 'id' in session:
        session.pop("id")
    return redirect(url_for('auth.login'))

app/templates/_table.html
{% if table %}
{% for row in table %}
<tr>
    {% for i in row %}
    <td>{{ i or '' }}</td>
    {% endfor %}
</tr>
{% endfor %}
{% endif %}

app/templates/base.html
{% from 'macro.html' import render_welcome %}
<!DOCTYPE html>

<html>
    <header>
        <meta charset="utf-8">
        <link rel="stylesheet" href="{{url_for('static',filename='css/font.css')}}" >
        {% if session["id"] | length != 4%}
        <link rel="stylesheet" href="{{url_for('static',filename='css/student.css')}}" >
        {% else %}
        <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}" >
        {% endif %}
        <title>主页</title>
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <link rel="stylesheet" href="{{url_for('static',filename='css/bootoast.css')}}">
        <link href="{{url_for('static',filename='pic/shortcut.ico')}}" rel="shortcut icon"/>
    
        <meta name="csrf-token" content="{{ csrf_token() }}">
        
    </header>
    <body class="container">
            <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item active" aria-current="page">{{render_welcome()}}</li>
                      <li class="breadcrumb-item"><a href="{{url_for('auth.logout')}}">退出</a></li>
                    </ol>
                  </nav>
    <div class="row">
    {% block body %}
    {% endblock %}
    </div>
    <script>
        function show_page_button(){
        $('#button_group').show()
        $nextpage = $('#nextpage')
        $lastpage = $('#lastpage')

        if (page >= pages || pages === 0)
            $nextpage.hide()
        else
            $nextpage.show()
        if (page == 1)
            $lastpage.hide()
        else
            $lastpage.show()     
    }
    </script>
    </body>
</html>

app/templates/macro.html
{% macro render_flied(flied,show_label = False) %}
    {% if show_label %}
        {{ flied.label}}
    {% endif %}

    {{ flied(class="form-control",**kwargs) }}
    {% for error in flied.errors %}
        <small class = "error" style="color: red">{{error}}</small>
    {% endfor %}
{% endmacro %}

{% macro render_welcome() %}
    欢迎
    {% if (session['id'] | length) == 4  %}
    {{ session['username'][0]}}老师
    {% else %}
    {{ session['username']}}学生
    {% endif %}
{% endmacro %}

app/templates/search_grade.html
    <div class="form-row">
            <div class="form-group col-md-2">
                    <input type="text" id="sno" class="form-control" placeholder="学号">
        </div>
        <div class="form-group col-md-2">
            <input type="text" id="sname" class="form-control" placeholder="姓名">
        </div>
        <div class="form-group col-md-3">
            <input type="text" id="cname" class="form-control" placeholder="课程名">
        </div>
        <div class="form-group col-md-2">
            <button id="search_grade" class="btn btn-primary">搜索</button>
        </div>
    </div>
<table class="table table-striped" id="gradetable">
    <thead>
        <tr>
            <th>学号</th>
            <th>名字</th>
            <th>课程名</th>
            <th>分数</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<div id="button_group" style="display: none">
        <button id="lastpage" class="btn btn-info">上一页</button>
        <button id="nextpage" class="btn btn-info">下一页</button>
</div>

<script>
        var csrftoken = $('meta[name=csrf-token]').attr('content')
        var page = 1
        var pages = 1
        var sname = ''
        var cno = ''
        var cname = ''

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
            }
        })
        function show_page_button(){
        $('#button_group').show()
        $nextpage = $('#nextpage')
        $lastpage = $('#lastpage')
        if (page == pages || pages === 0)
            $nextpage.hide()
        else
            $nextpage.show()
        if (page == 1)
            $lastpage.hide()
        else
            $lastpage.show()     
    }
    
    function pageChange(){
        var data = {
            'page' : page,
            'sname' : sname,
            'cno' : cno,
            'cname': cname,
        }
        $.ajax({
            type: "POST",
            url: search_grade_url,
            data: JSON.stringify(data),
            contentType: "application/json;charset=uft-8",
            success: function (data) {
                pages = data.pages
                $('tbody').html(data.html)
                show_page_button()
            }
        })
    }

    $('#nextpage').bind('click',function(){
        page = page + 1 
        pageChange();
    })

    $('#lastpage').bind('click',function(){
        page = page - 1 
        pageChange();
    })
</script>

app/templates/student/_grade.html
<div class="form-row">
   
    <div class="form-group col-md-3">
        <input type="text" id="cname" class="form-control" placeholder="课程名">
    </div>
    <div class="form-group col-md-2">
        <button id="search_grade" class="btn btn-primary">搜索</button>
    </div>
</div>
<table class="table table-striped" id="gradetable">
<thead>
    <tr>
        <th>学号</th>
        <th>名字</th>
        <th>课程名</th>
        <th>分数</th>
    </tr>
</thead>
<tbody>
</tbody>
</table>
<div id="button_group" style="display: none">
    <button id="lastpage" class="btn btn-info">上一页</button>
    <button id="nextpage" class="btn btn-info">下一页</button>
</div>

<script>
    var csrftoken = $('meta[name=csrf-token]').attr('content')
    var page = 0
    var pages = 1
    var cname = null

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
        }
    })
    function show_page_button(){
    $('#button_group').show()
    $nextpage = $('#nextpage')
    $lastpage = $('#lastpage')
    if (page == pages || pages === 0)
        $nextpage.hide()
    else
        $nextpage.show()
    if (page == 1)
        $lastpage.hide()
    else
        $lastpage.show()     
}

function pageChange(){
    var data = {
        'page' : page,
        'cname': cname,
    }
    $.ajax({
        type: "POST",
        url: search_grade_url,
        data: JSON.stringify(data),
        contentType: "application/json;charset=uft-8",
        success: function (data) {
            pages = data.pages
            $('tbody').html(data.html)
            show_page_button()
        }
    })
}

$('#nextpage').bind('click',function(){
    page = page + 1 
    pageChange();
})

$('#lastpage').bind('click',function(){
    page = page - 1 
    pageChange();
})
</script>

app/templates/student/_student_info.html
<table class="table table-striped">
        <tbody>
            <tr>
                <th>学号</th>
                <td>{{ info["sno"]}}</td>
                <th>姓名</th>
                <td>{{ info["sname"]}}</td>
            </tr>
            <tr>
                    <th>院系</th>
                    <td>{{ info["dname"]}}</td>
                    <th>宿舍号</th>
                    <td>{{ info["dormno"]}}</td>
            </tr>
            <tr>
                <th>性别</th>
                <td>{{ info["sex"]}}</td>
                <th>年龄</th>
                <td>{{ info["sage"]}}</td>
            </tr>
        </tbody>
    </table>

app/templates/student/index.html
{% extends'base.html' %}
{% block body %}
        <div class="col-3">
                <ul class="list-group">
                    <label class="list-group-item list-group-item-info"><span class="glyphicon glyphicon-search"></span>        查看</label>
                    <a href="#intro" class="list-group-item list-group-item-action">个人资料</a>
                    <a href="#grade_search" class="list-group-item list-group-item-action active">成绩查询</a>
                    <label class="list-group-item list-group-item-info"><span class="glyphicon glyphicon-user"></span>        个人信息</label>
                    <a href="#change_passwd" class="list-group-item list-group-item-action">修改密码</a>
                </ul>
        </div>

        <div class="col-7" id="main">
        </div>
        
        <script src="{{url_for('static',filename='js/script.js')}}" type="text/javascript" ></script>
        <script src="{{url_for('static',filename='js/bootoast.js')}}"></script>
        <script type="text/javascript" >
            var change_passwd_url = "{{ url_for('auth.change_passwd') }}" ;
            var search_grade_url = "{{url_for('student.search_grade')}}";
            var search_student_info_url = "{{ url_for('student.search_student_info')}}"
        </script>
        <script src="{{url_for('static',filename='js/student.js')}}"></script>

{% endblock %}

app/templates/student/test.html
<!DOCTYPE html>
{% from "macro.html" import render_flied %}
<html>
    <header>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>主页</title>
    </header>
    <body class="container">
            <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item active" aria-current="page">欢迎陈老师</li>
                      <li class="breadcrumb-item"><a href="#">退出</a></li>
                    </ol>
                  </nav>
        <div class="row">
        <div class="col-3">
                <ul class="list-group">
                   <a href="#" class="list-group-item list-group-item-action">修改密码</a>
                   <label class="list-group-item list-group-item-action list-group-item-info">管理</label>
                    <a href="#" class="list-group-item list-group-item-action">系别管理</a>
                    <a href="#" class="list-group-item list-group-item-action">课程管理</a>
                    <a href="#" class="list-group-item list-group-item-action">学籍管理</a>
                    <a href="#" class="list-group-item list-group-item-action">成绩管理</a>
                    <label class="list-group-item list-group-item-action list-group-item-info">查询</label>
                    <a href="#" class="list-group-item list-group-item-action">学生资料查询</a>
                    <a href="#" class="list-group-item list-group-item-action">学生成绩查询</a>
                </ul>
        </div>

        <div class="col-7" >
            <div class="container form-group">
                <form >
                    <div class="form-group row">
                    <label class="col-sm-2 col-form-label" >密码确定</label>
                    <div class="col-sm-6">
                   
                    </div>
                    </div>

                </form>
            </div>
        </div>
        </div>
    </body>
</html>